// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMessage struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	City                 *string  `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TestMessage) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

type TestRequest struct {
	Lower                *string  `protobuf:"bytes,1,req,name=lower" json:"lower,omitempty"`
	RepeatCount          *int32   `protobuf:"varint,2,opt,name=repeat_count,json=repeatCount,def=1" json:"repeat_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

const Default_TestRequest_RepeatCount int32 = 1

func (m *TestRequest) GetLower() string {
	if m != nil && m.Lower != nil {
		return *m.Lower
	}
	return ""
}

func (m *TestRequest) GetRepeatCount() int32 {
	if m != nil && m.RepeatCount != nil {
		return *m.RepeatCount
	}
	return Default_TestRequest_RepeatCount
}

type TestResponse struct {
	Value                *string  `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type CacheStats struct {
	Items                *int64   `protobuf:"varint,1,opt,name=items" json:"items,omitempty"`
	Bytes                *int64   `protobuf:"varint,2,opt,name=bytes" json:"bytes,omitempty"`
	Gets                 *int64   `protobuf:"varint,3,opt,name=gets" json:"gets,omitempty"`
	Hits                 *int64   `protobuf:"varint,4,opt,name=hits" json:"hits,omitempty"`
	Evicts               *int64   `protobuf:"varint,5,opt,name=evicts" json:"evicts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheStats) Reset()         { *m = CacheStats{} }
func (m *CacheStats) String() string { return proto.CompactTextString(m) }
func (*CacheStats) ProtoMessage()    {}
func (*CacheStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *CacheStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheStats.Unmarshal(m, b)
}
func (m *CacheStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheStats.Marshal(b, m, deterministic)
}
func (m *CacheStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheStats.Merge(m, src)
}
func (m *CacheStats) XXX_Size() int {
	return xxx_messageInfo_CacheStats.Size(m)
}
func (m *CacheStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheStats.DiscardUnknown(m)
}

var xxx_messageInfo_CacheStats proto.InternalMessageInfo

func (m *CacheStats) GetItems() int64 {
	if m != nil && m.Items != nil {
		return *m.Items
	}
	return 0
}

func (m *CacheStats) GetBytes() int64 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

func (m *CacheStats) GetGets() int64 {
	if m != nil && m.Gets != nil {
		return *m.Gets
	}
	return 0
}

func (m *CacheStats) GetHits() int64 {
	if m != nil && m.Hits != nil {
		return *m.Hits
	}
	return 0
}

func (m *CacheStats) GetEvicts() int64 {
	if m != nil && m.Evicts != nil {
		return *m.Evicts
	}
	return 0
}

type StatsResponse struct {
	Gets                 *int64      `protobuf:"varint,1,opt,name=gets" json:"gets,omitempty"`
	CacheHits            *int64      `protobuf:"varint,12,opt,name=cache_hits,json=cacheHits" json:"cache_hits,omitempty"`
	Fills                *int64      `protobuf:"varint,2,opt,name=fills" json:"fills,omitempty"`
	TotalAlloc           *uint64     `protobuf:"varint,3,opt,name=total_alloc,json=totalAlloc" json:"total_alloc,omitempty"`
	MainCache            *CacheStats `protobuf:"bytes,4,opt,name=main_cache,json=mainCache" json:"main_cache,omitempty"`
	HotCache             *CacheStats `protobuf:"bytes,5,opt,name=hot_cache,json=hotCache" json:"hot_cache,omitempty"`
	ServerIn             *int64      `protobuf:"varint,6,opt,name=server_in,json=serverIn" json:"server_in,omitempty"`
	Loads                *int64      `protobuf:"varint,8,opt,name=loads" json:"loads,omitempty"`
	PeerLoads            *int64      `protobuf:"varint,9,opt,name=peer_loads,json=peerLoads" json:"peer_loads,omitempty"`
	PeerErrors           *int64      `protobuf:"varint,10,opt,name=peer_errors,json=peerErrors" json:"peer_errors,omitempty"`
	LocalLoads           *int64      `protobuf:"varint,11,opt,name=local_loads,json=localLoads" json:"local_loads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetGets() int64 {
	if m != nil && m.Gets != nil {
		return *m.Gets
	}
	return 0
}

func (m *StatsResponse) GetCacheHits() int64 {
	if m != nil && m.CacheHits != nil {
		return *m.CacheHits
	}
	return 0
}

func (m *StatsResponse) GetFills() int64 {
	if m != nil && m.Fills != nil {
		return *m.Fills
	}
	return 0
}

func (m *StatsResponse) GetTotalAlloc() uint64 {
	if m != nil && m.TotalAlloc != nil {
		return *m.TotalAlloc
	}
	return 0
}

func (m *StatsResponse) GetMainCache() *CacheStats {
	if m != nil {
		return m.MainCache
	}
	return nil
}

func (m *StatsResponse) GetHotCache() *CacheStats {
	if m != nil {
		return m.HotCache
	}
	return nil
}

func (m *StatsResponse) GetServerIn() int64 {
	if m != nil && m.ServerIn != nil {
		return *m.ServerIn
	}
	return 0
}

func (m *StatsResponse) GetLoads() int64 {
	if m != nil && m.Loads != nil {
		return *m.Loads
	}
	return 0
}

func (m *StatsResponse) GetPeerLoads() int64 {
	if m != nil && m.PeerLoads != nil {
		return *m.PeerLoads
	}
	return 0
}

func (m *StatsResponse) GetPeerErrors() int64 {
	if m != nil && m.PeerErrors != nil {
		return *m.PeerErrors
	}
	return 0
}

func (m *StatsResponse) GetLocalLoads() int64 {
	if m != nil && m.LocalLoads != nil {
		return *m.LocalLoads
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TestMessage)(nil), "testpb.TestMessage")
	proto.RegisterType((*TestRequest)(nil), "testpb.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "testpb.TestResponse")
	proto.RegisterType((*CacheStats)(nil), "testpb.CacheStats")
	proto.RegisterType((*StatsResponse)(nil), "testpb.StatsResponse")
	proto.RegisterType((*Empty)(nil), "testpb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GroupCacheTestClient is the client API for GroupCacheTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupCacheTestClient interface {
	InitPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsResponse, error)
}

type groupCacheTestClient struct {
	cc *grpc.ClientConn
}

func NewGroupCacheTestClient(cc *grpc.ClientConn) GroupCacheTestClient {
	return &groupCacheTestClient{cc}
}

func (c *groupCacheTestClient) InitPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/testpb.GroupCacheTest/InitPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCacheTestClient) Get(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/testpb.GroupCacheTest/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCacheTestClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/testpb.GroupCacheTest/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupCacheTestServer is the server API for GroupCacheTest service.
type GroupCacheTestServer interface {
	InitPeers(context.Context, *Empty) (*Empty, error)
	Get(context.Context, *TestRequest) (*TestResponse, error)
	GetStats(context.Context, *Empty) (*StatsResponse, error)
}

func RegisterGroupCacheTestServer(s *grpc.Server, srv GroupCacheTestServer) {
	s.RegisterService(&_GroupCacheTest_serviceDesc, srv)
}

func _GroupCacheTest_InitPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCacheTestServer).InitPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testpb.GroupCacheTest/InitPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCacheTestServer).InitPeers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCacheTest_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCacheTestServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testpb.GroupCacheTest/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCacheTestServer).Get(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCacheTest_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCacheTestServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testpb.GroupCacheTest/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCacheTestServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupCacheTest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testpb.GroupCacheTest",
	HandlerType: (*GroupCacheTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitPeers",
			Handler:    _GroupCacheTest_InitPeers_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GroupCacheTest_Get_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _GroupCacheTest_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x51, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0x7b, 0x49, 0x2e, 0xe6, 0xe6, 0x52, 0x1f, 0xd6, 0x2a, 0x47, 0x45, 0x5a, 0x8e, 0x3e,
	0x14, 0x84, 0x48, 0x03, 0xbe, 0xf8, 0x26, 0xa5, 0xc4, 0x80, 0x82, 0x9c, 0xbe, 0x1f, 0xdb, 0x73,
	0x6c, 0x16, 0x36, 0xb7, 0xe7, 0xee, 0x24, 0x9a, 0x0f, 0xe4, 0x07, 0xf4, 0x1b, 0xc8, 0xce, 0xe4,
	0x6a, 0x23, 0xf4, 0x6d, 0xfe, 0xbf, 0x99, 0xf9, 0xdf, 0x7f, 0x6f, 0x17, 0x80, 0x30, 0xd0, 0xac,
	0xf3, 0x8e, 0x9c, 0x1a, 0xc7, 0xba, 0xbb, 0x2d, 0xdf, 0x42, 0xfe, 0x15, 0x03, 0x7d, 0xc2, 0x10,
	0xf4, 0x1d, 0x2a, 0x05, 0xa3, 0x56, 0xaf, 0xb1, 0x48, 0xce, 0x93, 0xcb, 0xac, 0xe2, 0x3a, 0xb2,
	0xc6, 0xd0, 0xae, 0x18, 0x08, 0x8b, 0x75, 0xb9, 0x94, 0xb5, 0x0a, 0x7f, 0x6c, 0x30, 0x90, 0x3a,
	0x81, 0xd4, 0xba, 0x9f, 0xe8, 0x8b, 0xe4, 0x7c, 0x70, 0x99, 0x55, 0x22, 0xd4, 0x05, 0x4c, 0x3d,
	0x76, 0xa8, 0xa9, 0x6e, 0xdc, 0xa6, 0x25, 0x36, 0x48, 0xdf, 0x25, 0x57, 0x55, 0x2e, 0xf8, 0x3a,
	0xd2, 0xf2, 0x02, 0xa6, 0x62, 0x15, 0x3a, 0xd7, 0x06, 0x8c, 0x5e, 0x5b, 0x6d, 0x37, 0x7d, 0x06,
	0x11, 0xe5, 0x2f, 0x80, 0x6b, 0xdd, 0xac, 0xf0, 0x0b, 0x69, 0x0a, 0x71, 0xc6, 0x10, 0xae, 0x03,
	0xcf, 0x0c, 0x2b, 0x11, 0x91, 0xde, 0xee, 0x08, 0x03, 0x7f, 0x68, 0x58, 0x89, 0x88, 0xf1, 0xef,
	0x90, 0x42, 0x31, 0x64, 0xc8, 0x75, 0x64, 0x2b, 0x43, 0xa1, 0x18, 0x09, 0x8b, 0xb5, 0x7a, 0x01,
	0x63, 0xdc, 0x9a, 0x86, 0x42, 0x91, 0x32, 0xdd, 0xab, 0xf2, 0xcf, 0x00, 0x8e, 0xf9, 0xab, 0xf7,
	0x09, 0x7b, 0xc7, 0xe4, 0x81, 0xe3, 0x2b, 0x80, 0x26, 0xe6, 0xab, 0xd9, 0x77, 0xca, 0x9d, 0x8c,
	0xc9, 0x07, 0x23, 0x81, 0xbf, 0x1b, 0x6b, 0xef, 0xa3, 0xb1, 0x50, 0x67, 0x90, 0x93, 0x23, 0x6d,
	0x6b, 0x6d, 0xad, 0x6b, 0x38, 0xe1, 0xa8, 0x02, 0x46, 0xef, 0x23, 0x51, 0x57, 0x00, 0x6b, 0x6d,
	0xda, 0x9a, 0x8d, 0x38, 0x6d, 0x3e, 0x57, 0x33, 0xb9, 0xba, 0xd9, 0xbf, 0xff, 0x51, 0x65, 0x71,
	0x8a, 0xb5, 0x7a, 0x03, 0xd9, 0xca, 0xd1, 0x7e, 0x23, 0x7d, 0x74, 0x63, 0xb2, 0x72, 0x24, 0x0b,
	0x2f, 0x21, 0x0b, 0xe8, 0xb7, 0xe8, 0x6b, 0xd3, 0x16, 0x63, 0x8e, 0x37, 0x11, 0xb0, 0x6c, 0xe5,
	0x62, 0xf5, 0xb7, 0x50, 0x4c, 0x24, 0x37, 0x8b, 0x78, 0xd8, 0x0e, 0xd1, 0xd7, 0xd2, 0xca, 0xe4,
	0xb0, 0x91, 0x7c, 0xe4, 0xf6, 0x19, 0xe4, 0xdc, 0x46, 0xef, 0x9d, 0x0f, 0x05, 0x70, 0x9f, 0x37,
	0x6e, 0x98, 0xc4, 0x01, 0xeb, 0x1a, 0x6d, 0xf7, 0x06, 0xb9, 0x0c, 0x30, 0x62, 0x87, 0xf2, 0x09,
	0xa4, 0x37, 0xeb, 0x8e, 0x76, 0xf3, 0xdf, 0x09, 0x3c, 0x5d, 0x78, 0xb7, 0xe9, 0x38, 0x6b, 0x7c,
	0x27, 0xea, 0x35, 0x64, 0xcb, 0xd6, 0xd0, 0x67, 0x44, 0x1f, 0xd4, 0x71, 0x7f, 0x34, 0x1e, 0x3f,
	0x3d, 0x94, 0xe5, 0x91, 0x9a, 0xc3, 0x70, 0x81, 0xa4, 0x9e, 0xf5, 0xfc, 0xc1, 0xa3, 0x3d, 0x3d,
	0x39, 0x84, 0x72, 0xb9, 0xbc, 0x33, 0x59, 0x20, 0xc9, 0x43, 0xfb, 0xcf, 0xff, 0x79, 0x2f, 0x0f,
	0x1e, 0x44, 0x79, 0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xf2, 0x4b, 0x18, 0x5b, 0x03, 0x00,
	0x00,
}
